apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: aura
  name: aura
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: aura
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: aura
    spec:
      containers:
      - image: us.gcr.io/new-eden-storage-a5c23/aura:v1.14
        imagePullPolicy: IfNotPresent
        name: aura
        ports:
        - containerPort: 8000
          protocol: TCP
